# Generated by Django 4.1 on 2023-11-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skosapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RDFFile",
        ),
    ]
